### ISSUE TITLE
Filepath for photos needs to be changed

### ISSUE THREAD

**Issue by grbarnas** [mfidino/uwin_issues#2]
V:\ should be changed to Z:\TransectTrailCamPics in the photos table

**Comment by llehrer** [comment]
uh oh

**Comment by mfidino** [comment]
Okay. I've updated the V:\ stuff to Z:\. Also, I accidentally rewrote the FileName in the process of doing this instead of the FilePath. I have now fixed this as well and have confirmed that the database can locate those files.

@grbarnas , can you go to the Visits form and check to see if you can see the images for R04-MAP1-JA18 from this form? I can see them on mine, but want to make sure that they can be seen on different computers before closing this issue.

**Comment by grbarnas** [comment]
I can see the images for R0**3**-MAP1-JA18 from the Visits form on my computer

**Comment by mfidino** [comment]
NOICE.

**Comment by llehrer** [comment]
takin care of business.

**Comment by mfidino** [comment]
![always be closing](https://user-images.githubusercontent.com/5490234/40205130-853ab506-59f0-11e8-8bff-533da130adb1.jpg)
)
